apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: web # Statefulset name
spec:
  selector:
    matchLabels:
      app: nginx
  serviceName: "nginx"
  replicas: 3 #
  minReadySeconds: 10
  template:
    metadata:
      labels:
        app: nginx
    spec:
      terminationGracePeriodSeconds: 10
      containers:
        - name: nginx
          image: registry.k8s.io/nginx-slim:0.8
          ports:
            - containerPort: 80
              name: web
          volumeMounts:
            - name: www
              mountPath: /usr/share/nginx/html
  volumeClaimTemplates:
    - metadata:
        name: www # volumeClaimTemplates(name)
      spec:
        accessModes: [ "ReadWriteOnce" ]
        storageClassName: "gp2"
        resources:
          requests:
            storage: 1Gi
# each three replicaset (pods) will have persistent volume type gp2 size 1 gb attached and mounted on path /usr/share/nginx/html
# followings are 2 prerequisites
# you need to add Amazon EBS CSI driver as add-on so that pod can create ebs volume
# Also, you need to assign AmazonEBSCSIDrivePolicy permission (in aws assigning permission means attaching policy) to role "eksctl-practice-nodegroup-ng-1-NodeInstanceRole"

